### ISSUE TITLE
[SUGGESTION] Ability to add other mods from curseforge 

### ISSUE THREAD

**Issue by NextRaven10** [MarkapToGo/mod-checker-reworked#2]
Ability to add other mods from curseforge for example: They could be downloaded when pressing the download all button

**Comment by MarkapToGo** [comment]
There is a new version on Modrinth! [Click here to get to Modrinth!](https://modrinth.com/mod/mod-checker-reworked/version/0.2 )

It may take a while until the new version is accepted on Modrinth!
